### ISSUE TITLE
Sipeed rv debugger lite

### ISSUE THREAD

**Issue by bfcs** [sipeed/Longan-DOC#6]
请问使用Sipeed rv debugger lite在PlatformIO下进行调试的教程何时更新啊，不知道如何配置

**Comment by asesidaa** [comment]
请问你找到教程了吗？

**Comment by bfcs** [comment]
> 请问你找到教程了吗？

我很久就不玩了

**Comment by lzimd** [comment]
1. 安装  FTDI drivers [link](http://www.ftdichip.com/Drivers/VCP.htm)，会看到「Sipeed-JTAG」和「Sipeed-Debug」变成「USB Serial Converter A」和「USB Serial Converter B」及「USB Serial Port」
2. 用 zadig 对「Sipeed-JTAG」替换为 WinUSB
3. 连线，按 [longan.sipeed.com / debug](https://longan.sipeed.com/zh/get_started/debug.html) 连
4. 如果是使用 platformIO
  a. platformio.ini, 配置 upload_protocol 和 debug_tool 为 sipeed-rv-debugger
  b. 找到 sipeed-rv-debugger.cfg ， 注释掉 ftdi_device_desc，或者将值改成 `Sipeed-Debug`
5. 如果是其他IDE，可按 openOCD 方式去配
